config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :islands, only: %i[index new create destroy show] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: [:update]
  resource :dashboard, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  before_create :set_total_price
  belongs_to :user
  belongs_to :island

  validates :start_date, presence: true
  validates :end_date, presence: true

  def set_total_price
    duration = (end_date - start_date).to_i
    total_price = duration * island.price_per_day
  end
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  has_one_attached :main_photo

  COUNTRIES = ["Isreal", "Spain", "Germany", "South Africa"]

  PHOTOS = ["https://www.treehugger.com/thmb/c8YBoBZfJLKUPGlFaQ7RT7J6xNA=/3840x2160/filters:fill(auto,1)/GettyImages-1296713537-aec94fc7c0154ed5812d2017e856f8d7.jpg",
    "https://cdn.cnn.com/cnnnext/dam/assets/180219103122-zanzibar-and-its-islands---mnemba-a-view-from-the-sky-mnemba-island-lodge.jpg",
    "https://www.treehugger.com/thmb/c8YBoBZfJLKUPGlFaQ7RT7J6xNA=/3840x2160/filters:fill(auto,1)/GettyImages-1296713537-aec94fc7c0154ed5812d2017e856f8d7.jpg",
    "https://cdn.cnn.com/cnnnext/dam/assets/180219103122-zanzibar-and-its-islands---mnemba-a-view-from-the-sky-mnemba-island-lodge.jpg"]


  validates :name, :territory, :price_per_day, :size, presence: true
  include PgSearch::Model

  pg_search_scope :global_search,
                  against: %i[name territory description],
                  associated_against: {
                    user: [:email]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :islands
  has_many :bookings
  has_many :received_bookings, through: :islands, source: :bookings

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.island = Island.find(params[:island_id])
    @booking.status = 'pending'
    if @booking.save
      redirect_to dashboard_path, notice: "Great your booking was created"
    else
      render "islands/show"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    redirect_to dashboard_path if @booking.save
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :state)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = current_user
    @applied_bookings = current_user.bookings
    @received_bookings = current_user.received_bookings
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :find_island, only: %i[edit destroy]

  def index
    if params[:query].present?
      @islands = Island.global_search(params[:query])
    else
      @islands = Island.all
    end
  end

  def show
    @island = Island.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user
    if @island.save
      redirect_to @island, notice: 'New island was created!'
    else
      render :new
    end
  end

  def destroy
    @island.destroy
    redirect_to islands_path, notice: "Island was deleted successfully"
  end

  private

  def find_island
    @island = Island.find(params[:id])
  end

  def island_params
    params.require(:island).permit(:name, :territory, :description, :price_per_day, :size, :main_photo, photos: [])
  end
end

# ARCHIVE

# def index_user
# @user_islands = current_user.islands
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<h1><%= @user.email %> dashboard</h1>

<h3>recieved bookings:</h3>
<% @received_bookings.each do |received_booking| %>
  <p>start date: <%= received_booking.start_date %></p>
  <p>end date: <%= received_booking.end_date %></p>
  <p>comment: <%= received_booking.comment %></p>
  <p>total price: <%= received_booking.total_price %></p>
  <% if received_booking.status == 'pending' %>
    <%= button_to 'accept', booking_path(received_booking, {status: 'accepted'}), method: :patch %>
    <%= button_to 'decline', booking_path(received_booking, {status: 'declined'}), method: :patch %>
  <% elsif received_booking.status == 'accepted' %>
    <p>accepted</p>
  <% else %>
    <p>declined</p>
  <% end %>
<% end %>


<h3>applied bookings</h3>
<% @applied_bookings.each do |applied_booking| %>
  <p>start date: <%= applied_booking.start_date %></p>
  <p>end date: <%= applied_booking.end_date %></p>
  <p>total price: <%= applied_booking.total_price %></p>
  <p>status: <%= applied_booking.status %></p>
<% end %>

<%= link_to 'Back to all the islands', islands_path %>
<%# display all recived/applied bookings %>
<%# for the recieved bookings - add accpt/regect btn %>
<%# applied bookings - see the status %>


<%# 1. define applied booking/recived bookings (user model) %>
<%# 2. add pending by default throught the bookings controller %>
<%# 3. add accpt/deny btn next to pending booking request %>

app/views/islands/edit.html.erb
<div class="container">
  <%= render "shared/form", island: @island %>
</div>

app/views/islands/index.html.erb
<br>
<br>
<br>
<br>
<h1>List of islands</h1>

<div class="index-top">
  <%= form_tag islands_path, method: :get do %>
  <div class="search-bar">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a island"
    %>
    <%= submit_tag "Search", class: "btn btn-primary", style: "margin: 0" %>
    </div>
  <% end %>
   <div>
      <%= link_to 'Create a new island', new_island_path, class: "btn btn-primary" %>
      <%= link_to 'Dashboard', dashboard_path, class: "btn btn-primary" %>
    </div>
 </div>
<div class="cards">
  <% @islands.each do |island| %>
    <div class="card-trip">
      <img src="https://images.unsplash.com/photo-1553603227-2358aabe821e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8aXNsYW5kfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" />
      <div class="card-trip-infos">
        <div class="island-info">
          <h2><%= link_to island.name, island_path(island) %></h2>
          <p><%= island.territory %></p>
          <p><%= island.description %></p>
          <p>Size: <%= island.size %></p>
        </div>
          <div class="card-trip-pricing">
            <p>
              <%= island.price_per_day%>
            </p>
            <% if island.avilable %>
              <p>Available</p>
            <% end %>
          </div>
      </div>
    </div>
  <% end %>
</div>



<% if params[:query].present? %>
  <%= link_to 'Back', islands_path %>
<% end %>

app/views/islands/new.html.erb
<div class="container">
  <%= render "shared/form" %>
</div>
<%= link_to 'Back', islands_path %>

app/views/islands/show.html.erb
<div class="container">
  <h1 style="text-align: center; color: black;"><strong><%= @island.name %></strong></h1>

  <div class="show-page-images">
    <% if @island.main_photo.present? %>
      <%= cl_image_tag @island.main_photo.key, class: "show-page-image-left" %>
    <% else %>
      <img src="https://media.nationalgeographic.org/assets/photos/000/268/26833.jpg" class="show-page-image-left">
    <% end  %>

    <div class="show-page-images-right">
      <% if @island.photos.present? %>
        <% n = @island.photos.length %>
        <% @island.photos.each do |photo| %>
          <%= cl_image_tag photo.key, class: "show-page-image-right" %>
          <% end %>
          <% if n < 4 %>
            <% Island::PHOTOS[n...4].each do |photo| %>
              <%= image_tag photo, class: "show-page-image-right" %>
            <% end  %>
          <% end  %>
      <% else %>
        <% Island::PHOTOS.each do |photo| %>
          <%= image_tag photo, class: "show-page-image-right" %>
        <% end  %>
      <% end %>
    </div>
  </div>

    <div>
  <h5 class="ititle">
    <strong><%= @island.name %>, <%= @island.territory %></strong>
    <p>$<%= @island.price_per_day %> Per Day, <%= @island.size %>sq</p>
      <%# <strong>Country:</strong> <%= @island.country %> <%#%>
      <center style="color: black;" class="description">
      <strong>• Description</strong>
      <br>
      <%= @island.description %>
      </center>
      <%# <strong>Price per day:</strong> <%= @island.price_per_day %> <%#%>
      <%# <strong>Is it avilable?</strong> <%= @island.avilable %> <%#%>
      <%# <strong>Size:</strong> <%= @island.size %> <%#%>
    </div>
</div>

<%# dose'nt ask me if i'm sure %>
<div class="islandact">
  <% if current_user == @island.user %>
    <%= link_to 'Delete', island_path(@island), method: :delete, data: {confirm: 'confirm delete'}, class: "btn1" %>
  <% end %>

  <% if current_user != @island.user %>
    <%=simple_form_for [@island, @booking] do |f|  %>
      <%=f.input :start_date  %>
      <%=f.input :end_date %>
      <%=f.input :comment %>
      <%=f.submit %>
    <% end %>
  <% end %>


    <button class="btn2" style="margin-left: 10px;"><%= link_to 'Back', islands_path %></button>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IslandBoi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= javascript_pack_tag 'application', "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="wrapper">
      <div class="main-content">
        <%= render 'shared/navbar' %>
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/hero" %>
<%# <%= render "shared/card" %>
<div class="containt-body">
<h2 class = 'Title'>Find the island of your dreams</h2>
<p><center>IslandBoi is the dream of every soul that desires a restful vacation.
<br>
Wether you're a a loner or a family member, you can alway find peace in your private island.
<br>
We know that different times in life won't really allow you to buy your private island,
<br>
therefore we came with the idea of renting your own island for the exact time and dates that you are looking for.
</center></p>
</div>
<div class="carousels">
<p id="home-text" >These are the steps to rent the island of your dreams: </p>
<br>
<section class="carousel" aria-label="Gallery">


  <ol class="carousel__viewport">

    <li id="carousel__slide1" style="background-image: url('https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Y29tcHV0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60');"
        tabindex="0"
        class="carousel__slide">
        <div class="carousel__slide--content">
          <p> Register as a user </p>
        </div>
      <div class="carousel__snapper">
        <a href="#carousel__slide4"
           class="carousel__prev">Go to last slide</a>
        <a href="#carousel__slide2"
           class="carousel__next">Go to next slide</a>
      </div>
    </li>
    <li id="carousel__slide2" style="background-image: url('https://media.istockphoto.com/photos/calendar-page-flipping-sheet-on-wood-table-background-business-picture-id1288509858?b=1&k=20&m=1288509858&s=170667a&w=0&h=YSB_acGyBTH8-gR87TbbQ5X4mYTVi-p6IxjzGM28RH8=');"
        tabindex="0"
        class="carousel__slide">
             <div class="carousel__slide--content">
          <p> Select the dates you want to go to your island  </p>
        </div>
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide1"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide3"
         class="carousel__next">Go to next slide</a>
    </li>
    <li id="carousel__slide3" style="background-image: url('https://images.unsplash.com/photo-1587538716374-408bb1118e67?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fGlzbGFuZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60');"
        tabindex="0"
        class="carousel__slide">
             <div class="carousel__slide--content">
          <p> Select your island  </p>
        </div>
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide2"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide4"
         class="carousel__next">Go to next slide</a>
    </li>
    <li id="carousel__slide4" style="background-image: url('https://media.istockphoto.com/photos/private-jet-on-airport-runway-picture-id1073242890?b=1&k=20&m=1073242890&s=170667a&w=0&h=X_7Sj3iXhKxRuSEWxPFUJnVAcVZ1AmG8eyaDjV3qFB4=');"
        tabindex="0"
        class="carousel__slide">
             <div class="carousel__slide--content">
          <p> Enjoy your trip </p>
        </div>
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide3"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide1"
         class="carousel__next">Go to first slide</a>
    </li>
  </ol>
  <aside class="carousel__navigation">
    <ol class="carousel__navigation-list">
      <li class="carousel__navigation-item">
        <a href="#carousel__slide1"
           class="carousel__navigation-button">Go to slide 1</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide2"
           class="carousel__navigation-button">Go to slide 2</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide3"
           class="carousel__navigation-button">Go to slide 3</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide4"
           class="carousel__navigation-button">Go to slide 4</a>
      </li>
    </ol>
  </aside>
</section>
<%# <p class ="carousel-text" id="home-text"> These are the steps to rent out your precious island</p>

<section class="carousel" aria-label="Gallery">
  <ol class="carousel__viewport">

    <li id="carousel__slide5" style="background-image: url('https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Y29tcHV0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60');"
        tabindex="0"
        class="carousel__slide">
        <div class="carousel__slide--content">
          <p>  Register as an owner of an island </p>
        </div>
      <div class="carousel__snapper">
        <a href="#carousel__slide8"
           class="carousel__prev">Go to last slide</a>
        <a href="#carousel__slide6"
           class="carousel__next">Go to next slide</a>
      </div>
    </li>
    <li id="carousel__slide6" style="background-image: url('https://media.istockphoto.com/photos/calendar-page-flipping-sheet-on-wood-table-background-business-picture-id1288509858?b=1&k=20&m=1288509858&s=170667a&w=0&h=YSB_acGyBTH8-gR87TbbQ5X4mYTVi-p6IxjzGM28RH8=');"
        tabindex="0"
        class="carousel__slide">
             <div class="carousel__slide--content">
          <p>
          Select the dates you want to rent out your island   </p>
        </div>
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide5"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide7"
         class="carousel__next">Go to next slide</a>
    </li>
    <li id="carousel__slide7" style="background-image: url('https://images.unsplash.com/photo-1564846824194-346b7871b855?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y29udHJhY3R8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60');"
        tabindex="0"
        class="carousel__slide">
             <div class="carousel__slide--content">
          <p>sign a contract with the tenant of your island </p>
        </div>
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide6"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide8"
         class="carousel__next">Go to next slide</a>
    </li>
    <li id="carousel__slide8" style="background-image: url('https://images.unsplash.com/photo-1587538716374-408bb1118e67?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fGlzbGFuZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60');"
        tabindex="0"
        class="carousel__slide">
             <div class="carousel__slide--content">
          <p> Rent out your island</p>
        </div>
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide7"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide5"
         class="carousel__next">Go to first slide</a>
    </li>
  </ol>
  <aside class="carousel__navigation">
    <ol class="carousel__navigation-list">
      <li class="carousel__navigation-item">
        <a href="#carousel__slide5"
           class="carousel__navigation-button">Go to slide 1</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide6"
           class="carousel__navigation-button">Go to slide 2</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide7"
           class="carousel__navigation-button">Go to slide 3</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide8"
           class="carousel__navigation-button">Go to slide 4</a>
      </li>
    </ol>
  </aside>
</section> %>
</div>
<div class="Island_owner">
<center>
<h1>Do you have an island you want to rent out?</h1>
<br>
<p>You can stop the lookout for clients!
<br>
IslandBoi allows you to literally find costumers to rent out your precsious Island!
</p>
<button class="btn1">I want to rent out my island</button>
</center>
</div>

app/views/shared/_card.html.erb
<div class="step-card">
  <div class="step-card__image">
    <%= step_name %>
  </div>
 <div class="step-card__content">
    <div class="step-card__content--header"><p><%#header %></p></div>
    <div class="step-card__content--sub-header"><p><%# subheader %></p></div>
    <img src=<%= "#{img_src}" %> alt = '' width="200px" height="200px">
    <h2 class ="step-card_content"></h2>
  <%= description %>



  </div>
</div>

<%# <%= testing %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-top">
    <div>
      <div class="footerbody">
        The best islands that you can find in the whole world
      </div>

      <div class ="footer-country">
          Where you to find us?
      </div>

      <div class="footer-content">
        <ul class="countries-list">
        <div>
            <li>Asia</li>
            <li>Africa</li>
            <li>America</li>
            <li>Caribbean</li>
          </div>
          <div>
            <li>Europe</li>
            <li>United States </li>
            <li>South America </li>
            <li>South Pacific</li>
          </div>
        </ul>
        <form action="#">
        <p> Subscribe to our newsletter </p>
          <input type="text" placeholder="Type email">
          <input type="submit">
        </form>
      </div>
    </div>
  </div>

  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_form.html.erb
<div id="form-container" class="container">
<br>
<br>
<br>
<br>
  <%= simple_form_for(@island) do |f| %>
    <div id="info">
      <%= f.input :name, placeholder: "" %>
      <%= f.input :territory, label: 'Country',
              input_html: { data: { geocoder_target: "country" }, class: 'd-none' },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
      <%= f.input :size, placeholder: "" %>
      <%= f.input :main_photo, as: :file, input_html: { multiple: false } %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.input :price_per_day, placeholder: "" %>
      <%= f.input :description, as: :text %>
      <%= f.submit "Submit", class: "button" %>
    </div>
  <% end %>
</div>




              <%# ARCHIVE %>

              <%# f.input :country, collection: Island::COUNTRIES %>

app/views/shared/_hero.html.erb
<div class="hero-image">
  <div class="hero-text">
      <div class="firsthead"><h1><strong>Looking for an Island?</strong></h1></div>
      <!--The centre text-->
      <div class="secondhead"><p><strong>A simplified way to rent the Island of your dreamds, right here, right now!</strong></p></div>
      <!--The centre text-->

      <div class="dropdown">
        <button class="dropbtn"><strong>Choose A Continent</strong></button>
        <div class="dropdown-content">
          <a href="#">Asia</a>
          <a href="#">Africa</a>
          <a href="#">Europe</a>
          <a href="#">North America</a>
          <a href="#">South America</a>
          <a href="#">Australia/Oceania</a>
          <a href="#">Antartica</a>
        </div>
      </div>

      <%# <div class="btn"><button class="btn1" style="margin:20px;"><strong>I have an island</strong></button><button class="btn2"><strong>I'm looking for an island</strong></button></div> %>
      <!--The part I want to change-->
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </li>
          <li class="nav-item dropdown">
            <i class="hamburger fa fa-bars avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", "#", class: "dropdown-item" %>
              <%= link_to "Contact", "#", class: "dropdown-item" %>
              <%= link_to "About", "#", class: "dropdown-item" %>
              <%= link_to "Islands", islands_path, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          </li>
          <li class="nav-item dropdown">
            <i class="hamburger fa fa-bars avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", "#", class: "dropdown-item" %>
              <%= link_to "Contact", "#", class: "dropdown-item" %>
              <%= link_to "About", "#", class: "dropdown-item" %>
              <%= link_to "Islands", islands_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>